SET SERVEROUTPUT ON;

DECLARE
    CURSOR C_EMPREGADOS IS
        SELECT FIRST_NAME, SALARY FROM HR.EMPLOYEES;

        V_NOME VARCHAR2(30);
        V_SALARY HR.EMPLOYEES.SALARY%TYPE;
        V_SALARIOTOTAL NUMBER (8,2);
BEGIN
    V_SALARIOTOTAL:=0;
    OPEN C_EMPREGADOS;
        LOOP
            FETCH C_EMPREGADOS INTO V_NOME, V_SALARY;

            DBMS_OUTPUT.PUT_LINE(V_NOME);
            V_SALARIOTOTAL:=V_SALARIOTOTAL+V_SALARY;

            EXIT WHEN C_EMPREGADOS%NOTFOUND;
        END LOOP;
        DBMS_OUTPUT.PUT_LINE(V_SALARIOTOTAL);

        CLOSE C_EMPREGADOS;
END;

-- Procedures

CREATE OR REPLACE PROCEDURE ADD_NOVO_JOGADOR
(
    JOGADOR_ID_IN IN NUMBER, 
    JOGADOR_NAME_IN IN VARCHAR2,
    JOGADOR_POS_IN IN NUMBER,
    JOGADOR_APELIDO_IN IN VARCHAR2)

IS
BEGIN
    INSERT INTO JOGADOR
    (ID_JOGADOR, NOME, POSICAO, NICKNAME)
    VALUES
    (JOGADOR_ID_IN, JOGADOR_NAME_IN , JOGADOR_POS_IN, JOGADOR_APELIDO_IN);
END;

-- Inserindo novas informações com Procedures.
SELECT * FROM JOGADOR;
EXEC ADD_NOVO_JOGADOR(3, 'JOGADOR 3', 99, 'INICIANTE');