SELECT * FROM HR.EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID
FROM HR.EMPLOYEES
WHERE MANAGER_ID IN (101, 145, 149); 

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID  
FROM HR.EMPLOYEES
WHERE MANAGER_ID NOT IN (101, 145, 149); 

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID  
FROM HR.EMPLOYEES
WHERE FIRST_NAME LIKE '%S%';

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID  
FROM HR.EMPLOYEES
WHERE FIRST_NAME NOT LIKE '%S%';

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID  
FROM HR.EMPLOYEES
WHERE SALARY BETWEEN 2500 AND 5000;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID  
FROM HR.EMPLOYEES
WHERE SALARY NOT BETWEEN 2500 AND 2600;

INSERT INTO JOGADOR 
(ID_JOGADOR, NOME, POSICAO, NICKNAME)
VALUES
(1, 'JOGADOR 1', 2, 'JOGADOR TÁTICO'); 

INSERT INTO CONTRATADO 
(ID_JOGADOR, DATA_INICIO, DATA_FIM)
VALUES
(1, TO_DATE ('09-02-2018'), TO_DATE ('09-02-2019'));

INSERT INTO CONSTRATADO 
(ID_JOGADOR, DATA_INICIO, DATA_FIM)
VALUES
(2, TO_DATE ('09-02-2020'), TO_DATE ('09-02-2023'));

SELECT * FROM JOGADOR
UPDATE JOGADOR 
SET NOME = 'ALEXANDER', POSICAO = 5
WHERE ID_JOGADOR = 1; 

SELECT * FROM CONTRATADO
DELETE FROM CONTRATADO 
WHERE ID_JOGADOR = 2;
 